version: '3.9'
services:
  db:
    image: postgres:15
    profiles:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharmacy
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "38273:38273" # backend.bodora.pl → localhost:38273
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "61973:61973" # smart.bodora.pl → localhost:61973
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
volumes:
  postgres_data:
