version: '3.9'
services:
  db:
    image: postgres:15
    profiles:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharmacy
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8000:8000"
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
volumes:
  postgres_data:
