name: CI No AI Self Heal

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: write
  pull-requests: write
  checks: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    outputs:
      failed: ${{ steps.detect.outputs.failed }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm ci --prefix frontend
      - name: Run tests
        id: tests
        continue-on-error: true
        run: |
          mkdir -p logs
          set -o pipefail
          npm test --prefix frontend -- --retry=2 2>&1 | tee logs/test.log
      - name: Run build
        id: build
        continue-on-error: true
        run: |
          set -o pipefail
          npm run build --prefix frontend 2>&1 | tee logs/build.log
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: logs
      - name: Detect failures
        id: detect
        run: |
          if [[ "${{ steps.tests.outcome }}" != 'success' || "${{ steps.build.outcome }}" != 'success' ]]; then
            echo "failed=1" >> $GITHUB_OUTPUT
          else
            echo "failed=0" >> $GITHUB_OUTPUT
          fi

  autofix-lint:
    needs: test-build
    if: needs.test-build.outputs.failed == '1'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run eslint
        run: npx eslint frontend --ext .js,.ts,.tsx --fix || true
      - name: Run prettier
        run: npx prettier "frontend/**/*.{js,ts,tsx,jsx,json,css,md}" --write || true
      - name: Check git diff
        id: git-diff
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Commit and open PR
        if: steps.git-diff.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        run: |
          timestamp=$(date -u +'%Y%m%d%H%M%S')
          branch="autofix/lint-$timestamp"
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git checkout -b "$branch"
          git commit -am "chore: automatic lint/format fixes"
          git push origin "$branch"
          gh pr create --title "chore: automatic lint/format fixes" --body "Automated lint/format fixes" --base master --head "$branch"
      - name: Fail if no PR created
        if: steps.git-diff.outputs.changed == 'false'
        run: exit 1
