name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      HEADLESS: true
      DB_URL: sqlite+aiosqlite:///tmp/test.db
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-ci.txt

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install commitlint dependencies
        run: npm ci

      - name: Lint commits
        run: npx commitlint --from=HEAD~1 --to=HEAD

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Run tests
        run: bash scripts/run_ci_tests.sh
