name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      HEADLESS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-ci.txt
          playwright install --with-deps chromium

      - name: Run tests
        run: bash scripts/run_ci_tests.sh
