name: CI (scraper)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install commitlint
        run: npm i -D @commitlint/cli @commitlint/config-conventional

      # Sprawdź WSZYSTKIE commity w PR
      - name: Lint commits (PR)
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.sha }}

      # Sprawdź zakres push
      - name: Lint commits (push)
        if: github.event_name == 'push'
        run: |
          BASE="${{ github.event.before }}"
          HEAD="${{ github.sha }}"
          npx commitlint --from "$BASE" --to "$HEAD"

  lint_and_test:
    name: Lint & Tests (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: commitlint
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12']

    env:
      CI: true
      HEADLESS: true
      DB_URL: sqlite+aiosqlite:///tmp/test.db
      # Ułatwienie dla testów Selenium:
      CHROME_BIN: /usr/bin/google-chrome
      CHROMEDRIVER_PATH: /usr/local/bin/chromedriver

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Cache pip (extra)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >-
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ hashFiles('**/requirements*.txt') }}-
            ${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install system deps for headless browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxss1 libnss3 libasound2 libgbm1 libu2f-udev \
            fonts-liberation xdg-utils xvfb

      # Chrome + ChromeDriver dla Selenium
      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: latest

      - name: Verify Chrome & Driver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Upgrade pip tooling
        run: python -m pip install --upgrade pip wheel setuptools

      - name: Install Python dependencies
        run: |
          if [ -f "requirements-ci.txt" ]; then pip install -r requirements-ci.txt; fi
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
          # Narzędzia CI, jeśli nie ma ich w requirements
          pip install ruff pytest pytest-cov mypy||true

      - name: Setup Node (frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Ruff (lint)
        run: ruff check .
        continue-on-error: false

      - name: mypy (optional)
        run: |
          if [ -f "mypy.ini" ] || grep -q "\[tool\.mypy\]" pyproject.toml 2>/dev/null; then
            mypy .
          else
            echo "No mypy config found — skipping."
          fi
        continue-on-error: true

      # Jeśli Twoje testy Selenium wymagają Xvfb, odkomentuj poniższe i opakuj run_ci_tests.sh:
      # - name: Run tests (with Xvfb)
      #   run: xvfb-run -a bash scripts/run_ci_tests.sh

      - name: Run tests
        run: bash scripts/run_ci_tests.sh

      # Artefakty: coverage.xml i JUnit, jeśli generujesz
      - name: Upload coverage
        if: always() && hashFiles('**/coverage.xml') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: "**/coverage.xml"
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload junit
        if: always() && hashFiles('**/junit*.xml') != ''
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.python-version }}
          path: |
            **/junit*.xml
            **/test-results/**/*.xml
          if-no-files-found: ignore
          retention-days: 7
