name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: true
      HEADLESS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-ci.txt
          playwright install --with-deps chromium

      - name: Run scraper integration tests
        run: bash scripts/run_ci_tests.sh

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.REGISTRY }}/backend:latest

      - name: Build and push scraper image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: scraper/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY }}/scraper:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Push to deployment repository
        run: |
          git remote add deploy ${{ secrets.DEPLOY_REPO }}
          git push deploy main
