name: Load Tests

on:
  workflow_dispatch:

jobs:
  loadtest:
    runs-on: ubuntu-latest
    env:
      LOCUST_HOST: http://localhost:8000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Locust
        run: pip install locust
      - name: Run load test
        run: locust -f loadtests/locustfile.py --headless -u 10 -r 10 -t 1m --host $LOCUST_HOST --exit-code-on-error 0
