name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract changelog section for tag
        id: changelog
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "Creating release notes for tag: $TAG"
          awk -v tag="$TAG" '
            $0 ~ "^## " tag "\\b" {found=1; next}
            /^## / && found { exit }
            found { print }
          ' CHANGELOG.md > release_body.md || true
          if [ ! -s release_body.md ]; then
            echo "No dedicated section found; using full CHANGELOG"
            cp CHANGELOG.md release_body.md
          fi
          echo "release_body=release_body.md" >> $GITHUB_OUTPUT

      - name: Create Release from tag
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          body_path: ${{ steps.changelog.outputs.release_body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
