name: Scheduled Scraper

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build scraper image
        run: docker build -t scraper -f scraper/Dockerfile .

      - name: Run scraper
        env:
          DB_URL: ${{ secrets.DB_URL }}
          HEADLESS: true
        run: |
          docker run --rm \
            -e DB_URL \
            -e HEADLESS \
            scraper \
            python -m scraper.cli.scrape_all
